import type { President } from '../types/president'

export const mockPresidents: President[] = [
  {
    id: 1,
    name: '乔治·华盛顿',
    nameEn: 'George Washington',
    term: '1789-1797',
    termStart: 1789,
    termEnd: 1797,
    party: '无党派',
    vicePresident: '约翰·亚当斯',
    birthDate: '1732-02-22',
    deathDate: '1799-12-14',
    birthPlace: '弗吉尼亚州威斯特摩兰县',
    education: '未接受正规大学教育',
    career: '军人、政治家',
    achievements: '领导美国独立战争，担任首任美国总统，确立总统任期不超过两届的传统',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg/440px-Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg',
    description: '乔治·华盛顿是美国的开国元勋之一，被称为"美国国父"。他在1775年至1783年美国独立战争期间担任大陆军总司令，1787年主持制宪会议制定了美国宪法。1789年，他经过全体选举团无异议的支持而成为美国第一任总统。他在两届的任期中设立了许多持续到今天的政策和传统。'
  },
  {
    id: 2,
    name: '约翰·亚当斯',
    nameEn: 'John Adams',
    term: '1797-1801',
    termStart: 1797,
    termEnd: 1801,
    party: '联邦党',
    vicePresident: '托马斯·杰斐逊',
    birthDate: '1735-10-30',
    deathDate: '1826-07-04',
    birthPlace: '马萨诸塞州布伦特里',
    education: '哈佛大学',
    career: '律师、政治家',
    achievements: '参与起草《独立宣言》，美国第二任总统',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0c/John_Adams_A18236.jpg/440px-John_Adams_A18236.jpg',
    description: '约翰·亚当斯是美国第一任副总统，后当选为美国第二任总统。他是《独立宣言》的签署者之一，被美国人视为开国元勋之一。他的长子约翰·昆西·亚当斯后来成为美国第六任总统。'
  },
  {
    id: 3,
    name: '托马斯·杰斐逊',
    nameEn: 'Thomas Jefferson',
    term: '1801-1809',
    termStart: 1801,
    termEnd: 1809,
    party: '民主共和党',
    vicePresident: '艾伦·伯尔、乔治·克林顿',
    birthDate: '1743-04-13',
    deathDate: '1826-07-04',
    birthPlace: '弗吉尼亚州沙德维尔',
    education: '威廉与玛丽学院',
    career: '律师、建筑师、政治家',
    achievements: '起草《独立宣言》，路易斯安那购地案，创立弗吉尼亚大学',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Thomas_Jefferson_by_Rembrandt_Peale%2C_1800.jpg/440px-Thomas_Jefferson_by_Rembrandt_Peale%2C_1800.jpg',
    description: '托马斯·杰斐逊是美国第三任总统，同时也是《美国独立宣言》的主要起草人，美国开国元勋之一。他在任期间从法国手中购买了路易斯安那领地，使美国领土扩大了近一倍。'
  },
  {
    id: 16,
    name: '亚伯拉罕·林肯',
    nameEn: 'Abraham Lincoln',
    term: '1861-1865',
    termStart: 1861,
    termEnd: 1865,
    party: '共和党',
    vicePresident: '汉尼巴尔·哈姆林、安德鲁·约翰逊',
    birthDate: '1809-02-12',
    deathDate: '1865-04-15',
    birthPlace: '肯塔基州霍金维尔',
    education: '自学成才',
    career: '律师、政治家',
    achievements: '废除奴隶制，维护国家统一，领导北方赢得南北战争',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Abraham_Lincoln_O-77_matte_collodion_print.jpg/440px-Abraham_Lincoln_O-77_matte_collodion_print.jpg',
    description: '亚伯拉罕·林肯是美国第16任总统。在其总统任内，美国爆发了内战，史称南北战争。林肯击败了南方分离势力，废除了奴隶制度，维护了国家的统一。但就在内战结束后不久，他不幸遇刺身亡，是第一位遭到刺杀的美国总统。'
  },
  {
    id: 26,
    name: '西奥多·罗斯福',
    nameEn: 'Theodore Roosevelt',
    term: '1901-1909',
    termStart: 1901,
    termEnd: 1909,
    party: '共和党',
    vicePresident: '无（1901-1905）、查尔斯·W·费尔班克斯',
    birthDate: '1858-10-27',
    deathDate: '1919-01-06',
    birthPlace: '纽约州纽约市',
    education: '哈佛大学',
    career: '军人、探险家、政治家',
    achievements: '巴拿马运河开凿，反垄断政策，建立国家公园体系',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Theodore_Roosevelt%2C_1904.jpg/440px-Theodore_Roosevelt%2C_1904.jpg',
    description: '西奥多·罗斯福是美国第26任总统，人称"老罗斯福"。他因成功调停日俄战争而获得1906年诺贝尔和平奖。在总统任期内，他对内实施反垄断政策，对外推行扩张主义政策，开凿了巴拿马运河。'
  },
  {
    id: 32,
    name: '富兰克林·D·罗斯福',
    nameEn: 'Franklin D. Roosevelt',
    term: '1933-1945',
    termStart: 1933,
    termEnd: 1945,
    party: '民主党',
    vicePresident: '约翰·N·加纳、亨利·A·华莱士、哈里·S·杜鲁门',
    birthDate: '1882-01-30',
    deathDate: '1945-04-12',
    birthPlace: '纽约州海德公园',
    education: '哈佛大学、哥伦比亚法学院',
    career: '律师、政治家',
    achievements: '推行新政应对大萧条，领导美国参与二战，建立社会保障体系',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/FDR_1944_Color_Portrait.jpg/440px-FDR_1944_Color_Portrait.jpg',
    description: '富兰克林·德拉诺·罗斯福是美国第32任总统，也是美国历史上唯一连任超过两届的总统，总共连任四届。在20世纪30年代经济大萧条期间，他推行了新政以复苏经济。第二次世界大战期间，他领导美国经历了史无前例的全球性战争。'
  },
  {
    id: 35,
    name: '约翰·F·肯尼迪',
    nameEn: 'John F. Kennedy',
    term: '1961-1963',
    termStart: 1961,
    termEnd: 1963,
    party: '民主党',
    vicePresident: '林登·B·约翰逊',
    birthDate: '1917-05-29',
    deathDate: '1963-11-22',
    birthPlace: '马萨诸塞州布鲁克莱恩',
    education: '哈佛大学',
    career: '军人、作家、政治家',
    achievements: '阿波罗计划，建立和平队，古巴导弹危机处理',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/John_F._Kennedy%2C_White_House_color_photo_portrait.jpg/440px-John_F._Kennedy%2C_White_House_color_photo_portrait.jpg',
    description: '约翰·菲茨杰拉德·肯尼迪是美国第35任总统，在他任期内发生了古巴导弹危机、柏林墙的建立、太空竞赛、越南战争的早期活动以及美国民权运动。1963年11月22日，肯尼迪在得克萨斯州达拉斯市遇刺身亡，成为美国历史上最著名的事件之一。'
  },
  {
    id: 40,
    name: '罗纳德·里根',
    nameEn: 'Ronald Reagan',
    term: '1981-1989',
    termStart: 1981,
    termEnd: 1989,
    party: '共和党',
    vicePresident: '乔治·H·W·布什',
    birthDate: '1911-02-06',
    deathDate: '2004-06-05',
    birthPlace: '伊利诺伊州坦皮科',
    education: '尤里卡学院',
    career: '演员、播音员、政治家',
    achievements: '里根经济学，结束冷战，重建美国军事力量',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Official_Portrait_of_President_Reagan_1981.jpg/440px-Official_Portrait_of_President_Reagan_1981.jpg',
    description: '罗纳德·威尔逊·里根是美国第40任总统。在任期间，他实行供给侧经济政策，人称"里根经济学"，大幅降低税率，推动经济复苏。对外政策上，他提出星球大战计划，对苏联采取强硬立场，被认为是结束冷战的关键人物之一。'
  },
  {
    id: 44,
    name: '贝拉克·奥巴马',
    nameEn: 'Barack Obama',
    term: '2009-2017',
    termStart: 2009,
    termEnd: 2017,
    party: '民主党',
    vicePresident: '乔·拜登',
    birthDate: '1961-08-04',
    deathDate: '在世',
    birthPlace: '夏威夷州檀香山市',
    education: '哥伦比亚大学、哈佛法学院',
    career: '律师、教授、政治家',
    achievements: '奥巴马医改，结束伊拉克战争，恢复美国经济',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/President_Barack_Obama.jpg/440px-President_Barack_Obama.jpg',
    description: '贝拉克·侯赛因·奥巴马是美国第44任总统，也是美国历史上首位非裔总统。在任期间，他推动了美国医疗体系的重大改革，签署了《患者保护与平价医疗法案》，在应对金融危机、气候变化等问题上发挥了重要作用。'
  },
  {
    id: 45,
    name: '唐纳德·特朗普',
    nameEn: 'Donald Trump',
    term: '2017-2021',
    termStart: 2017,
    termEnd: 2021,
    party: '共和党',
    vicePresident: '迈克·彭斯',
    birthDate: '1946-06-14',
    deathDate: '在世',
    birthPlace: '纽约州纽约市皇后区',
    education: '宾夕法尼亚大学沃顿商学院',
    career: '企业家、电视名人、政治家',
    achievements: '减税政策，推动制造业回流，中东和平协议',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Donald_Trump_official_portrait.jpg/440px-Donald_Trump_official_portrait.jpg',
    description: '唐纳德·约翰·特朗普是美国第45任总统。他在从政前是一位商人和电视名人。在任期间，他推行了一系列保护主义政策，包括贸易战、减税政策、限制移民等。他的总统任期充满争议，是美国历史上第一位被弹劾两次的总统。'
  },
  {
    id: 46,
    name: '乔·拜登',
    nameEn: 'Joe Biden',
    term: '2021-至今',
    termStart: 2021,
    termEnd: 2026,
    party: '民主党',
    vicePresident: '卡玛拉·哈里斯',
    birthDate: '1942-11-20',
    deathDate: '在世',
    birthPlace: '宾夕法尼亚州斯克兰顿',
    education: '特拉华大学、雪城大学法学院',
    career: '律师、政治家',
    achievements: '应对新冠疫情，基础设施投资法案，气候政策',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Joe_Biden_presidential_portrait.jpg/440px-Joe_Biden_presidential_portrait.jpg',
    description: '约瑟夫·罗宾内特·拜登是美国第46任总统。他曾担任奥巴马政府的副总统，在任期间致力于应对新冠疫情、推动基础设施建设、应对气候变化等议题。他以78岁的年龄成为美国历史上就职时年龄最大的总统。'
  }
]

export const partyColors: { [key: string]: string } = {
  '无党派': '#808080',
  '联邦党': '#000080',
  '民主共和党': '#006400',
  '民主党': '#0015BC',
  '共和党': '#FF0000',
  '辉格党': '#8B4513'
}
